-- AlterTable
ALTER TABLE "Job" ADD COLUMN     "latitude" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "longitude" DOUBLE PRECISION DEFAULT 0;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "latitude" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "longitude" DOUBLE PRECISION DEFAULT 0;
